# Generated by Django 4.1.5 on 2023-01-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzrasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('uzrasas', models.TextField(blank=True, help_text='Pagrindinis užrašo tekstas', max_length=500, null=True, verbose_name='Užrašas')),
                ('nuotrauka', models.ImageField(blank=True, null=True, upload_to='uzrasu_nuotraukos', verbose_name='Nuotrauka')),
                ('data_sukurimo', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='UzrasoKategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(max_length=50, verbose_name='Užrašo kategorija')),
            ],
        ),
    ]
