# Generated by Django 4.1.5 on 2023-01-18 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uzrasokategorija',
            name='kategorijos_autorius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uzrasas',
            name='uzraso_autorius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uzrasas',
            name='uzraso_kategorija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.uzrasokategorija'),
        ),
    ]
